In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN


In [3]:
df.shape

(569, 33)

In [4]:
df.drop(columns = ['id', 'Unnamed: 32'], inplace = True)

In [5]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678


In [6]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

### Scaling

In [7]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [10]:
X_train[:5]

array([[-3.82333646e-01, -3.52757971e-01, -4.36108887e-01,
        -4.18509899e-01, -1.26475994e+00, -1.09853871e+00,
        -9.21293397e-01, -7.71516141e-01, -1.25902708e+00,
        -1.04611666e+00, -3.84838057e-01, -6.12970674e-01,
        -3.67200360e-01, -3.60857323e-01,  1.20835156e-01,
        -7.58543946e-01, -8.49488029e-01, -1.00173784e+00,
        -1.48701734e-01, -9.65970770e-01, -4.88861435e-01,
        -7.53672453e-01, -5.30729581e-01, -4.97873148e-01,
        -1.13674996e+00, -9.82593006e-01, -1.10380163e+00,
        -1.16870672e+00, -1.16356524e+00, -1.28202011e+00],
       [-7.92025185e-01, -8.70823690e-01, -7.46674787e-01,
        -7.25593677e-01, -9.30095548e-01,  1.07632469e-01,
         1.22804432e-01, -5.41432133e-01, -1.74146819e-02,
         1.32066228e+00, -2.64590517e-01, -2.68690284e-01,
        -1.51548769e-01, -3.66407808e-01,  1.20611213e+00,
         2.18460468e+00,  1.95348834e+00,  1.38803340e+00,
        -9.96072064e-01,  3.01830712e+00, -8.55456815e-

In [11]:
y_train

429    B
388    B
495    B
400    M
374    B
      ..
35     M
68     B
195    B
63     B
462    B
Name: diagnosis, Length: 455, dtype: object

### Label Encoding

In [12]:
y_train = LabelEncoder().fit_transform(y_train)
y_test = LabelEncoder().fit_transform(y_test)

In [13]:
y_train

array([0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1,
       1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1,

### Numpy arrays to PyTorch tensors

In [14]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [15]:
X_train_tensor.shape

torch.Size([455, 30])

In [16]:
y_train_tensor.shape

torch.Size([455])

### Defining the Model

In [41]:
class BreastCancerNN():
    def __init__(self, X):

        self.weights = torch.rand(X.shape[1], 1, dtype = torch.float64, requires_grad = True)
        self.bias = torch.zeros(1, dtype = torch.float64, requires_grad = True)

    def forward(self, X):
        z = torch.matmul(X, self.weights) + self.bias
        y_pred = torch.sigmoid(z)
        return y_pred

    def loss_function(self, y_pred, y):
        epsilon = 1e-7
        y_pred = torch.clamp(y_pred, epsilon, 1-epsilon)

        loss = -(y * torch.log(y_pred) + (1 - y) * torch.log(1 - y_pred)).mean()
        return loss
    
    

### Important Parameeter

In [65]:
learning_rate = 0.1
epochs = 500

## Training Pipeline

In [66]:
# create model
model = BreastCancerNN(X_train_tensor)

#define loop
for epoch in range(epochs):
    # forward pass
    y_pred = model.forward(X_train_tensor)

    # loss calculate
    loss = model.loss_function(y_pred, y_train_tensor)
    print(f'Epoch {epoch+1}/{epochs}, Loss: {loss.item()}')

    # backward pass
    loss.backward()

    # parameter update
    with torch.no_grad():
        model.weights -= learning_rate * model.weights.grad
        model.bias -= learning_rate * model.bias.grad

    model.weights.grad.zero_()
    model.bias.grad.zero_()

    # print loss in each epoch
    print(f'Epoch {epoch+1}/{epochs}, Loss: {loss.item()}')

Epoch 1/500, Loss: 3.887866562923082
Epoch 1/500, Loss: 3.887866562923082
Epoch 2/500, Loss: 3.7696428582748323
Epoch 2/500, Loss: 3.7696428582748323
Epoch 3/500, Loss: 3.6466382304820995
Epoch 3/500, Loss: 3.6466382304820995
Epoch 4/500, Loss: 3.5180128271808746
Epoch 4/500, Loss: 3.5180128271808746
Epoch 5/500, Loss: 3.388255795959296
Epoch 5/500, Loss: 3.388255795959296
Epoch 6/500, Loss: 3.257204434316756
Epoch 6/500, Loss: 3.257204434316756
Epoch 7/500, Loss: 3.12059609271143
Epoch 7/500, Loss: 3.12059609271143
Epoch 8/500, Loss: 2.9745086152949507
Epoch 8/500, Loss: 2.9745086152949507
Epoch 9/500, Loss: 2.825183927939035
Epoch 9/500, Loss: 2.825183927939035
Epoch 10/500, Loss: 2.674023000819219
Epoch 10/500, Loss: 2.674023000819219
Epoch 11/500, Loss: 2.5232620587608534
Epoch 11/500, Loss: 2.5232620587608534
Epoch 12/500, Loss: 2.3706659925213636
Epoch 12/500, Loss: 2.3706659925213636
Epoch 13/500, Loss: 2.212552384888073
Epoch 13/500, Loss: 2.212552384888073
Epoch 14/500, Loss: 

In [67]:
model.bias

tensor([-0.5554], dtype=torch.float64, requires_grad=True)

### Evaluation

In [68]:
# model evaluation

with torch.no_grad():
    y_pred = model.forward(X_test_tensor)
    y_pred = (y_pred > 0.5).float()
    accuracy = (y_pred == y_test_tensor).float().mean()
    print(f'Accuracy: {accuracy.item()*100:.2f}%')


Accuracy: 59.65%
