In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN


In [3]:
df.shape

(569, 33)

In [4]:
df.drop(columns = ['id', 'Unnamed: 32'], inplace = True)

In [5]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678


In [6]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

### Scaling

In [40]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train).astype(np.float32)
X_test = scaler.transform(X_test).astype(np.float32)

In [41]:
X_train[:5]

array([[ 1.82626474e+00,  5.28421998e-01,  1.86654627e+00,
         1.80749345e+00,  1.44540071e+00,  1.58213913e+00,
         2.10517073e+00,  2.65957999e+00,  2.74413443e+00,
         5.12083232e-01,  6.23955667e-01, -3.53074342e-01,
         5.88647008e-01,  6.35569990e-01, -5.51227629e-01,
        -6.43679872e-02, -2.85784923e-03,  3.29244256e-01,
         8.56257915e-01, -1.77391350e-01,  1.92564678e+00,
         9.93097842e-01,  1.95274842e+00,  1.92639279e+00,
         1.14989185e+00,  1.21105874e+00,  1.22275913e+00,
         2.37580967e+00,  4.25089550e+00,  9.75566268e-01],
       [-1.09057456e-01,  9.23325598e-01, -1.63700968e-01,
        -2.02390030e-01, -2.70072103e-01, -6.91328645e-01,
        -7.32041001e-01, -6.14996254e-01, -5.33323646e-01,
        -7.12478459e-01, -1.89596146e-01,  2.07481399e-01,
        -3.73169929e-01, -1.75006062e-01, -4.12122816e-01,
        -2.45654836e-01, -3.72934669e-01, -4.17482972e-01,
         3.92188244e-02, -4.54144150e-01, -1.62847415e-

In [42]:
y_train

array([1., 0., 1., 0., 0., 1., 1., 0., 0., 1., 1., 0., 1., 0., 1., 0., 0.,
       1., 1., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0.,
       0., 0., 1., 1., 1., 1., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0.,
       1., 1., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
       1., 0., 1., 0., 1., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 1., 1., 0., 1., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1.,
       1., 1., 0., 0., 0., 0., 0., 0., 1., 1., 0., 1., 0., 0., 0., 1., 1.,
       0., 1., 1., 0., 0., 1., 0., 0., 0., 1., 0., 1., 1., 1., 0., 0., 0.,
       0., 0., 1., 0., 1., 1., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 1., 1., 1., 0., 1., 1., 0.,
       0., 1., 1., 0., 1.

### Label Encoding

In [43]:
y_train = LabelEncoder().fit_transform(y_train).astype(np.float32)
y_test = LabelEncoder().fit_transform(y_test).astype(np.float32)

In [44]:
y_train

array([1., 0., 1., 0., 0., 1., 1., 0., 0., 1., 1., 0., 1., 0., 1., 0., 0.,
       1., 1., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0.,
       0., 0., 1., 1., 1., 1., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0.,
       1., 1., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
       1., 0., 1., 0., 1., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 1., 1., 0., 1., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1.,
       1., 1., 0., 0., 0., 0., 0., 0., 1., 1., 0., 1., 0., 0., 0., 1., 1.,
       0., 1., 1., 0., 0., 1., 0., 0., 0., 1., 0., 1., 1., 1., 0., 0., 0.,
       0., 0., 1., 0., 1., 1., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 1., 1., 1., 0., 1., 1., 0.,
       0., 1., 1., 0., 1.

### Numpy arrays to PyTorch tensors

In [45]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [46]:
type(y_train_tensor)

torch.Tensor

In [47]:
y_train_tensor.shape

torch.Size([455])

In [48]:
X_test_tensor.shape

torch.Size([114, 30])

In [49]:
X_train_tensor.dtype

torch.float32

In [50]:
X_test_tensor.dtype

torch.float32

In [51]:
y_test_tensor.dtype

torch.float32

### Defining the Model

In [66]:
import torch.nn as nn

class BreastCancerNN(nn.Module):
    def __init__(self, num_features):
        
        super().__init__()
        self.linear = nn.Linear(num_features, 1)
        self.sigmoid = nn.Sigmoid()
    
    def forward(self, features):
        out = self.linear(features)
        out = self.sigmoid(out)
        return out

### Important Parameeter

In [67]:
learning_rate = 0.1
epochs = 500

In [68]:
loss_function = nn.BCELoss()

In [69]:
type(loss_function)

torch.nn.modules.loss.BCELoss

## Training Pipeline

In [70]:
import torch.optim as optim

In [71]:
# create model
model = BreastCancerNN(X_train_tensor.shape[1])
optimizer = optim.SGD(model.parameters(), lr = learning_rate)

#define loop
for epoch in range(epochs):
    # forward pass
    y_pred = model(X_train_tensor)

    # loss calculate
    loss = loss_function(y_pred, y_train_tensor.view(-1, 1))

    # backward pass
    loss.backward()

    # parameter update
    optimizer.step()

    optimizer.zero_grad()

    # print loss in each epoch
    print(f'Epoch {epoch+1}/{epochs}, Loss: {loss.item()}')

Epoch 1/500, Loss: 0.9906812310218811
Epoch 2/500, Loss: 0.6757814288139343
Epoch 3/500, Loss: 0.5066936016082764
Epoch 4/500, Loss: 0.41761988401412964
Epoch 5/500, Loss: 0.36451664566993713
Epoch 6/500, Loss: 0.3288916051387787
Epoch 7/500, Loss: 0.3029826879501343
Epoch 8/500, Loss: 0.2830488681793213
Epoch 9/500, Loss: 0.2670827805995941
Epoch 10/500, Loss: 0.25391021370887756
Epoch 11/500, Loss: 0.24279433488845825
Epoch 12/500, Loss: 0.23324614763259888
Epoch 13/500, Loss: 0.2249264419078827
Epoch 14/500, Loss: 0.2175912857055664
Epoch 15/500, Loss: 0.21106000244617462
Epoch 16/500, Loss: 0.20519542694091797
Epoch 17/500, Loss: 0.1998913735151291
Epoch 18/500, Loss: 0.19506393373012543
Epoch 19/500, Loss: 0.19064588844776154
Epoch 20/500, Loss: 0.1865827441215515
Epoch 21/500, Loss: 0.1828295737504959
Epoch 22/500, Loss: 0.17934909462928772
Epoch 23/500, Loss: 0.17611001431941986
Epoch 24/500, Loss: 0.17308591306209564
Epoch 25/500, Loss: 0.170254185795784
Epoch 26/500, Loss: 0.1

In [72]:
model.linear.weight

Parameter containing:
tensor([[ 0.5355,  0.5667,  0.4263,  0.5068,  0.2494, -0.0114,  0.5513,  0.7127,
          0.0820, -0.3626,  0.5452, -0.0070,  0.4062,  0.4196,  0.0494, -0.1471,
         -0.1677, -0.0947, -0.2323, -0.3951,  0.7008,  0.6816,  0.8570,  0.8281,
          0.6474,  0.1269,  0.4650,  0.6648,  0.4696,  0.0873]],
       requires_grad=True)

### Evaluation

In [73]:
# model evaluation

with torch.no_grad():
    y_pred = model.forward(X_test_tensor)
    y_pred = (y_pred >= 0.5).float()
    accuracy = (y_pred == y_test_tensor).float().mean()
    print(f'Accuracy: {accuracy.item()*100:.2f}%')


Accuracy: 51.35%
