In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN


In [3]:
df.shape

(569, 33)

In [4]:
df.drop(columns = ['id', 'Unnamed: 32'], inplace = True)

In [5]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678


In [6]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

### Scaling

In [7]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train).astype(np.float32)
X_test = scaler.transform(X_test).astype(np.float32)

In [8]:
X_train[:5]

array([[ 9.62894201e-01,  3.28349799e-01,  1.00468719e+00,
         8.29095483e-01,  1.12339091e+00,  1.20308638e+00,
         1.24985194e+00,  1.43836939e+00,  6.08949244e-01,
        -1.32110626e-01,  1.39442527e+00,  3.41300428e-01,
         1.28087533e+00,  1.10407102e+00,  6.54457092e-01,
         1.38740170e+00,  7.43254781e-01,  1.08512628e+00,
        -3.14125180e-01,  4.44895089e-01,  8.21589172e-01,
        -1.08826116e-01,  7.21639276e-01,  6.90064311e-01,
         4.15516406e-01,  6.08980536e-01,  4.33842719e-01,
         5.36399364e-01, -7.36200392e-01, -3.55666816e-01],
       [ 1.24001765e+00, -5.32685637e-01,  1.16895103e+00,
         1.14731264e+00,  6.76162779e-01,  1.05546169e-01,
         7.36354768e-01,  9.54349637e-01,  5.90047538e-01,
        -6.22010529e-02,  1.04951394e+00,  6.75981224e-01,
         9.67141509e-01,  1.03140998e+00,  3.45974624e-01,
        -2.51772821e-01,  7.72314742e-02,  6.89248919e-01,
         2.54165065e-02,  2.97003895e-01,  1.18625045e+

In [9]:
y_train

156    M
121    M
46     B
78     M
216    B
      ..
145    B
310    B
243    B
7      M
220    B
Name: diagnosis, Length: 455, dtype: object

### Label Encoding

In [10]:
y_train = LabelEncoder().fit_transform(y_train).astype(np.float32)
y_test = LabelEncoder().fit_transform(y_test).astype(np.float32)

In [11]:
y_train

array([1., 1., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 1., 1., 0., 0., 0.,
       1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 0.,
       0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0., 1., 0., 1.,
       0., 1., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0., 1., 0., 0.,
       0., 1., 0., 0., 1., 1., 0., 0., 1., 0., 0., 1., 1., 0., 0., 1., 0.,
       1., 0., 0., 1., 0., 0., 0., 1., 0., 0., 1., 1., 0., 0., 0., 1., 0.,
       1., 0., 1., 0., 0., 0., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0.,
       0., 1., 1., 0., 0., 0., 0., 1., 1., 0., 1., 0., 0., 0., 1., 0., 1.,
       0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0.,
       1., 1., 1., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 1., 1., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0.,
       1., 1., 0., 0., 1., 1., 0., 1., 1., 0., 1., 0., 1., 0., 0., 0., 0.,
       0., 0., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
       0., 0., 1., 1., 1.

### Numpy arrays to PyTorch tensors

In [12]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [13]:
type(y_train_tensor)

torch.Tensor

In [14]:
y_train_tensor.shape

torch.Size([455])

In [15]:
X_test_tensor.shape

torch.Size([114, 30])

In [16]:
X_train_tensor.dtype

torch.float32

In [17]:
X_test_tensor.dtype

torch.float32

In [18]:
y_test_tensor.dtype

torch.float32

In [19]:
from torch.utils.data import Dataset, DataLoader

class CustomDataset(Dataset):
    def __init__(self, features, labels):
        self.features = features
        self.labels = labels
    
    def __len__(self):
        return self.features.shape[0]
    
    def __getitem__(self, index):
        return self.features[index], self.labels[index]

In [20]:
train_dataset = CustomDataset(X_train_tensor, y_train_tensor)
test_dataset = CustomDataset(X_test_tensor, y_test_tensor)

In [21]:
train_dataset[10]

(tensor([-0.5556, -0.6754, -0.5644, -0.5550, -0.3268, -0.7047, -0.7084, -0.6960,
         -0.3399, -0.5069, -0.5693, -0.3521, -0.5675, -0.4638, -0.7256, -0.4138,
         -0.4644, -0.6378, -0.8126, -0.5450, -0.4814, -0.4240, -0.5559, -0.5028,
         -0.6527, -0.4560, -0.5012, -0.4503, -0.4699, -0.4287]),
 tensor(0.))

In [22]:
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=False)

### Defining the Model

In [23]:
import torch.nn as nn

class BreastCancerNN(nn.Module):
    def __init__(self, num_features):
        
        super().__init__()
        self.linear = nn.Linear(num_features, 1)
        self.sigmoid = nn.Sigmoid()
    
    def forward(self, features):
        out = self.linear(features)
        out = self.sigmoid(out)
        return out

### Important Parameeter

In [24]:
learning_rate = 0.1
epochs = 500

In [25]:
loss_function = nn.BCELoss()

In [26]:
type(loss_function)

torch.nn.modules.loss.BCELoss

## Training Pipeline

In [27]:
import torch.optim as optim

In [28]:
# create model
model = BreastCancerNN(X_train_tensor.shape[1])
optimizer = optim.SGD(model.parameters(), lr = learning_rate)

#define loop
for epoch in range(epochs):
    for batch_features, batch_labels in train_loader:
        # forward pass
        y_pred = model(batch_features)

        # loss calculate
        loss = loss_function(y_pred, batch_labels.view(-1, 1))

        # backward pass
        loss.backward()

        # parameter update
        optimizer.step()

        optimizer.zero_grad()

    # print loss in each epoch
    print(f'Epoch {epoch+1}/{epochs}, Loss: {loss.item()}')

Epoch 1/500, Loss: 0.14295364916324615
Epoch 2/500, Loss: 0.17704012989997864
Epoch 3/500, Loss: 0.3270171582698822
Epoch 4/500, Loss: 0.06417589634656906
Epoch 5/500, Loss: 0.0316922590136528
Epoch 6/500, Loss: 0.12730802595615387
Epoch 7/500, Loss: 0.008829724974930286
Epoch 8/500, Loss: 0.07238442450761795
Epoch 9/500, Loss: 0.07802511006593704
Epoch 10/500, Loss: 0.1402594894170761
Epoch 11/500, Loss: 0.09697290509939194
Epoch 12/500, Loss: 0.1598176807165146
Epoch 13/500, Loss: 0.04167436808347702
Epoch 14/500, Loss: 0.010273496620357037
Epoch 15/500, Loss: 0.12743057310581207
Epoch 16/500, Loss: 0.013255784288048744
Epoch 17/500, Loss: 0.02678643725812435
Epoch 18/500, Loss: 0.06819013506174088
Epoch 19/500, Loss: 0.07455166429281235
Epoch 20/500, Loss: 0.07176252454519272
Epoch 21/500, Loss: 0.003990861587226391
Epoch 22/500, Loss: 0.0031018147710710764
Epoch 23/500, Loss: 0.05389998108148575
Epoch 24/500, Loss: 0.03296787291765213
Epoch 25/500, Loss: 0.010505813173949718
Epoch 

In [29]:
model.linear.weight

Parameter containing:
tensor([[ 0.1510,  0.4066,  0.1205,  0.4109, -0.0805, -1.1943,  1.2293,  1.4868,
         -0.2703, -0.3016,  2.0965, -0.4095,  1.1223,  1.4789,  0.3158, -0.8636,
          0.1544,  0.1923, -0.4354, -0.9899,  1.4656,  1.6755,  0.9384,  1.4607,
          1.0713, -0.1520,  1.2078,  1.1903,  0.8747,  0.7423]],
       requires_grad=True)

### Evaluation

In [31]:
# model evaluation
model.eval()
accuracy_list = []

with torch.no_grad():
    for batch_features, batch_labels in test_loader:
        y_pred = model(batch_features)
        y_pred = (y_pred >= 0.5).float()
        batch_accuracy = (y_pred.view(-1) == batch_labels).float().mean().item()
        accuracy_list.append(batch_accuracy)

overall_accuracy = sum(accuracy_list) / len(accuracy_list)
print(f'Accuracy: {overall_accuracy*100:.2f}%')


Accuracy: 96.44%
